### ISSUE TITLE
Authentication not persistent after restart of node server

### ISSUE THREAD

**Issue by m-gagne** [Missing-Children-Society-Canada/portal-node#1]
Either using `node server.js` or `nodemon server.js` to run the app, whenever code changes forcing a restart of the application the currently logged in user is forced to re-authenticate.

## Expected behavior:

- Because passport is configured to us cookies and the `nonceLifetime` is set to a day, I expect the user to still be authenticate.

## Actual behavior:

- When code changes and `nodemon` reloads the application the user is forced to re-authenticate

## Steps taken to resolve

- Tried to do everything listed [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-openidconnect-nodejs) & [here](https://github.com/AzureAD/passport-azure-ad) to ensure that we are not using in memory session state but rather cookie state to store the auth token.

**Comment by jefking** [comment]
@m-gagne is this still an issue?

**Comment by jefking** [comment]
I haven't seen this in a month. Closing
