### ISSUE TITLE
Readme: Getting Started

### ISSUE THREAD

**Issue by jefking** [Missing-Children-Society-Canada/portal-node#6]
We need comments on how to get this running for new people to start contributing.

- npm install
- configuration; needed and how to set it up.

The biggest issue is authentication; as right now we are bound to a specific tenant with a single user.

**Comment by vatdaell** [comment]
I'll work on this and other readmes

**Comment by jefking** [comment]
@vatdaell any progress on this?

**Comment by vatdaell** [comment]
@jefking Hey I have been extremely busy after work this month, I couldn't get much done but I am free now and I have started working on it

**Comment by jefking** [comment]
As we have had a number of people get started with this, and they have not bugged any specific issues. I am going to close this.
